# docker-compose.yml
version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres-db
    build: ./db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata:
    driver: local
  app:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24