# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: daymohk-app
    image: daymohk-app
    build: .
    ports:
      - ${PORT}:${PORT}
    # depends_on:
    #   - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
      - net
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
  # db:
  #   container_name: ${POSTGRES_HOST}
  #   image: ${POSTGRES_HOST}
  #   build: ./db
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - net
  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_LOGIN}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #   ports:
  #     - ${PGADMIN_PORT}
volumes:
  pgdata:
    driver: local
  app:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
