# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: daymohk-app
    image: daymohk-app
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
      - net
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
  db:
      container_name: ${POSTGRES_HOST}
      image: ${POSTGRES_HOST}
      build: ./db
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - net
 
volumes:
  pgdata:
    driver: local
  app:

networks:
  net:
    driver: bridge
